Repository ALGOHAZA-Study/Algorithm-Study, pull requests merged in 2024-04, with the labels that each got.

#2 기본 파일들 생성
  .gitignore
  assets/image/How_to_fork_repo/fork_repo_1.png
  assets/image/How_to_fork_repo/fork_repo_10.png
  assets/image/How_to_fork_repo/fork_repo_11.png
  assets/image/How_to_fork_repo/fork_repo_12.png
  assets/image/How_to_fork_repo/fork_repo_2.png
  assets/image/How_to_fork_repo/fork_repo_3.png
  assets/image/How_to_fork_repo/fork_repo_4.png
  assets/image/How_to_fork_repo/fork_repo_5.png
  assets/image/How_to_fork_repo/fork_repo_6.png
  assets/image/How_to_fork_repo/fork_repo_7.png
  assets/image/How_to_fork_repo/fork_repo_8.png
  assets/image/How_to_fork_repo/fork_repo_9.png
  docs/how_to/How_to_fork_repo.md
Labels: Contributes

#3 `HowTo-PR` 및 `PR` 규칙, 템플릿 작성 완료
  assets/image/How_to_contribute/contribute_1.png
  assets/image/How_to_contribute/contribute_2.png
  assets/image/How_to_contribute/contribute_3.png
  assets/image/How_to_contribute/contribute_4.png
  assets/image/How_to_contribute/contribute_5.png
  assets/image/How_to_contribute/contribute_6.png
  assets/image/How_to_contribute/contribute_7.png
  assets/image/How_to_contribute/contribute_8.png
  assets/image/How_to_contribute/contribute_9.png
  docs/how_to/How_to_contribute.md
  docs/pull_request_template.md
  docs/rules/github_repository/pr_rules.md
Labels: Contributes

#4 기본 파일 추가
  README.md
  assets/README.md
  assets/example/P_2609/README.md
  assets/example/P_2609/Solution_2609.java
  assets/example/P_2609/approval_2609.PNG
  assets/image/logo.png
  docs/README.md
  docs/how_to/How_to_contribute.md
  docs/how_to/How_to_fork_repo.md
  docs/pull_request_template.md
  docs/rules/github_repository/commit_and_organization.md
  docs/rules/github_repository/pr_rules.md
  jbw9964/M_2024_04/Week_2/P_2609/README.md
  jbw9964/M_2024_04/Week_2/P_2609/Solution_2609.java
  jbw9964/M_2024_04/Week_2/P_2609/approval_2609.PNG
Labels: Contributes

#7 `feat` : 도메인, 템플릿 개선
  README.md
  assets/example/README.md
Labels: Contributes

#5 [2024/04/17] - C++ : 1 문제 / [uuccu]
  uuccu/M_2024_04/Week_3/P_24512/README.md
  uuccu/M_2024_04/Week_3/P_24512/image.png
  uuccu/M_2024_04/Week_3/P_24512/sol.cc
Labels: Backtracking, BAJ

#9 `[2024/04/15]` - `Java` : `2 문제` / `[jbw9964]`
  jbw9964/M_2024_04/Week_3/P_14888/Main.java
  jbw9964/M_2024_04/Week_3/P_14888/README.md
  jbw9964/M_2024_04/Week_3/P_14888/approval_14888.png
  jbw9964/M_2024_04/Week_3/P_16987/Main.java
  jbw9964/M_2024_04/Week_3/P_16987/README.md
  jbw9964/M_2024_04/Week_3/P_16987/approval_16987.png
Labels: Backtracking, Bruteforce, BAJ

#10 [2024/04/20] - c++: 1문제 / [mungjin01]
  mungjin01/M_2024_04/Week_3/P_2579/README.md
  mungjin01/M_2024_04/Week_3/P_2579/Solution_2579.cpp
  mungjin01/M_2024_04/Week_3/P_2579/approval_2579.png
  mungjin01/M_2024_04/Week_4/P_1074/README.md
  mungjin01/M_2024_04/Week_4/P_1074/Solution_1074.cpp
  mungjin01/M_2024_04/Week_4/P_1074/approval_1074.png
Labels: DP, BAJ

#15 [2024/04/24] - C++ : 3문제 / [uuccu]
  uuccu/M_2024_04/Week_4/P_15486/README.md
  uuccu/M_2024_04/Week_4/P_15486/image.png
  uuccu/M_2024_04/Week_4/P_15486/sol.cc
  uuccu/M_2024_04/Week_4/P_most_distance_node/README.md
  uuccu/M_2024_04/Week_4/P_most_distance_node/image.png
  uuccu/M_2024_04/Week_4/P_most_distance_node/sol.cc
  uuccu/M_2024_04/Week_4/P_ranking/README.md
  uuccu/M_2024_04/Week_4/P_ranking/image.png
  uuccu/M_2024_04/Week_4/P_ranking/sol.cc
Labels: BFS, DFS, DP, BAJ

#14 [2024/04/24] - c++ : 1문제 / sikca]
  Sikca/M_2024_04/Week_4/P_14725/README.md
  Sikca/M_2024_04/Week_4/P_14725/image.png
  Sikca/M_2024_04/Week_4/P_14725/solution.cpp
  Sikca/M_2024_04/Week_4/P_4587/README.md
  Sikca/M_2024_04/Week_4/P_4587/image.png
  Sikca/M_2024_04/Week_4/P_4587/solution.cpp
Labels: Greedy, Mathematics, BAJ

#17 [2024/04/27] - c++ 1문제 / [sikca]
  Sikca/M_2024_04/Week_4/P_14066/README.md
  Sikca/M_2024_04/Week_4/P_14066/image.png
  Sikca/M_2024_04/Week_4/P_14066/solution.cpp
  Sikca/M_2024_04/Week_4/P_14725/README.md
Labels: Implements, BAJ

#18 [2024/04/27] - Java : 5 문제 / [jbw9964]
  jbw9964/M_2024_04/Week_4/P_1038/Main.java
  jbw9964/M_2024_04/Week_4/P_1038/README.md
  jbw9964/M_2024_04/Week_4/P_1038/approval_1038.PNG
  jbw9964/M_2024_04/Week_4/P_15993/Main.java
  jbw9964/M_2024_04/Week_4/P_15993/README.md
  jbw9964/M_2024_04/Week_4/P_15993/approval_15993.PNG
  jbw9964/M_2024_04/Week_4/P_1958/Main.java
  jbw9964/M_2024_04/Week_4/P_1958/README.md
  jbw9964/M_2024_04/Week_4/P_1958/approval_1958.png
  jbw9964/M_2024_04/Week_4/P_5373/Main.java
  jbw9964/M_2024_04/Week_4/P_5373/README.md
  jbw9964/M_2024_04/Week_4/P_5373/approval_5373.png
  jbw9964/M_2024_04/Week_4/P_9251/Main.java
  jbw9964/M_2024_04/Week_4/P_9251/README.md
  jbw9964/M_2024_04/Week_4/P_9251/approval_9251.png
Labels: DP, Implements, BAJ
